/vis/open OGL
/control/saveHistory

/vis/drawVolume worlds
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate

/vis/viewer/set/background white
/vis/geometry/set/colour all -1 0 0 0

/vis/scene/add/axes
/vis/geometry/set/colour lead 0 0.5 0.5 0.5
/vis/geometry/set/forceSolid lead
/vis/geometry/set/colour plastic 0 0.1 0.5 0.5
/vis/geometry/set/forceSolid plastic
/vis/scene/add/date
/vis/scene/add/hits